# Parse data structure into a pandas DataFrame
Parse data paths from the Smart-Kages folder structure and store them in a pandas DataFrames.

Also, load time adjustments to help estimate start and end times for each 1-hour segment.

In [1]:
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sleap_io as sio
from tqdm import tqdm

from smart_kages_movement.datetime import (
    extract_datetimes,
    extract_frame_timestamps,
    find_segment_overlaps,
)
from smart_kages_movement.io import (
    get_video_shape,
    parse_data_into_df,
    save_segment_timestamps,
)
from smart_kages_movement.plots import show_first_frame_corner

## Configuration
Define some global variables and paths.

In [2]:
# Path to the data directory containing all kages.
data_dir = Path.home() / "Data" / "Smart-Kages" / "2024-Jul-Sep"
assert data_dir.exists(), f"Data directory {data_dir} does not exist."

# Path for saving the processed data (in this case, a subfolder of 'data_dir').
save_dir = data_dir / "movement_analysis"
save_dir.mkdir(parents=True, exist_ok=True)

# Set to True for faster processing with multiple cores.
# Set to False if ProcessPoolExecutor is causing errors on your system.
USE_MULTIPROCESSING = True

## Aggregate segment paths into a single dataframe

The data is stored per Smart-Kage, in folders names as `kageN`, e.g. `kage1`, `kage2`, etc.

Each Smart-Kage folder contains:
- daily videos are stored in `videos/YYYY/MM/DD/`, split into 1-hour segments. Each 1-hour segment is an `.mp4` file named `kageN_YYYYMMDD_HHMMSS.mp4`.
- corresponding DeepLabCut (DLC) predictions are stored in `analysis/dlc_output/YYYY/MM/DD/`. Each 1-hour `.h5` file therein is prefixed with `kageN_YYYYMMDD_HHMMSS`.

Let's parse the relevant parts of the data structure into a single dataframe.

In [3]:
df = parse_data_into_df(data_dir)
df.head()

Found 3 kage directories:  kage1 kage22 kage28
Found a total of 3449 .h5 pose files output by DLC.

                         start_datetime  \
kage  date     hour
kage1 20240723 11   2024-07-23 11:01:03
               12   2024-07-23 12:01:04
               13   2024-07-23 13:01:03
               14   2024-07-23 14:01:03
               15   2024-07-23 15:01:03

                                                        pose_file_path  \
kage  date     hour
kage1 20240723 11    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               12    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               14    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

                                                       video_file_path
kage  date     hour
kage1 20240723 11    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               12    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               14    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

## Add some video metadata
We reach each video's `n_frames`, `height`, `width`, and `n_channels` from the video file itself, using `sleap-io`.

These metadata are added as columns to the dataframe.

In [4]:
video_paths = df["video_file_path"].tolist()

# Get video shapes (optionally with parallel processing)
video_shapes = [None] * len(video_paths)
if USE_MULTIPROCESSING:
    with ProcessPoolExecutor() as ex:
        futures = {ex.submit(get_video_shape, p): i for i, p in enumerate(video_paths)}
        for fut in tqdm(as_completed(futures), total=len(futures)):
            i = futures[fut]
            video_shapes[i] = fut.result()
else:
    for i, p in enumerate(tqdm(video_paths)):
        video_shapes[i] = get_video_shape(p)

# Store video shapes in the dataframe
video_shapes_df = pd.DataFrame(
    video_shapes,
    index=df.index,
    columns=["n_frames", "height", "width", "n_channels"],
)
df = pd.concat([df, video_shapes_df], axis=1)

100%|██████████| 3449/3449 [00:10<00:00, 326.67it/s]

Let's see if there are any videos where `n_channels` is not 3, which would indicate a non-RGB video.

In [5]:
df_non_rgb = df.copy()[df["n_channels"] != 3]
print(f"Found {len(df_non_rgb)} non-RGB videos.")
df_non_rgb.head(len(df_non_rgb))

Found 25 non-RGB videos.

                          start_datetime  \
kage   date     hour
kage28 20240726 16   2024-07-26 16:01:04
       20240728 15   2024-07-28 15:01:03
       20240804 00   2024-08-04 00:01:04
       20240807 18   2024-08-07 18:01:03
       20240809 23   2024-08-09 23:01:03
       20240811 21   2024-08-11 21:01:03
       20240812 00   2024-08-12 00:01:04
       20240814 23   2024-08-14 23:01:03
       20240817 22   2024-08-17 22:01:03
       20240818 20   2024-08-18 20:01:04
       20240823 19   2024-08-23 19:01:03
                20   2024-08-23 20:01:03
       20240827 15   2024-08-27 15:01:03
                17   2024-08-27 17:01:04
       20240828 13   2024-08-28 13:01:03
                15   2024-08-28 15:01:03
       20240829 15   2024-08-29 15:01:03
       20240831 18   2024-08-31 18:01:03
       20240902 19   2024-09-02 19:01:03
       20240903 16   2024-09-03 16:01:04
       20240905 19   2024-09-05 19:01:03
       20240906 15   2024-09-06 15:01:04
       20240907 17   2024-09-07 17:01:03
       20240908 15   2024-09-08 15:01:03
       20240909 15   2024-09-09 15:01:04

                                                         pose_file_path  \
kage   date     hour
kage28 20240726 16    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240728 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240804 00    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240807 18    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240809 23    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240811 21    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240812 00    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240814 23    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240817 22    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240818 20    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240823 19    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
                20    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240827 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
                17    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240828 13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
                15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240829 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240831 18    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240902 19    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240903 16    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240905 19    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240906 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240907 17    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240908 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240909 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

                                                        video_file_path  \
kage   date     hour
kage28 20240726 16    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240728 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240804 00    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240807 18    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240809 23    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240811 21    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240812 00    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240814 23    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240817 22    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240818 20    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240823 19    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
                20    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240827 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
                17    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240828 13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
                15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240829 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240831 18    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240902 19    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240903 16    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240905 19    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240906 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240907 17    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240908 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
       20240909 15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

                      n_frames  height  width  n_channels
kage   date     hour
kage28 20240726 16        7017     376    500           1
       20240728 15        7039     376    500           1
       20240804 00        7032     376    500           1
       20240807 18        7041     376    500           1
       20240809 23        7042     376    500           1
       20240811 21        7037     376    500           1
       20240812 00        7031     376    500           1
       20240814 23        7008     376    500           1
       20240817 22        7047     376    500           1
       20240818 20        7030     376    500           1
       20240823 19        7040     376    500           1
                20        7036     376    500           1
       20240827 15        7036     376    500           1
                17        7036     376    500           1
       20240828 13        7017     376    500           1
                15        7052     376    500           1
       20240829 15        7042     376    500           1
       20240831 18        7033     376    500           1
       20240902 19        7052     376    500           1
       20240903 16        7052     376    500           1
       20240905 19        7032     376    500           1
       20240906 15        7036     376    500           1
       20240907 17        7051     376    500           1
       20240908 15        7040     376    500           1
       20240909 15        7044     376    500           1

## Adjust datetimes for each segment
Above, we derived the start datetime of each video from its filename.
However, this is usually not the exact time when the video started recording.

We can find the exact start time for each video, as well as the exact timestamps for each frame, by inspecting two sources:

1. The `adjustments.txt` file. There is one per day, stored in `kageN/videos/YYYY/MM/DD/`, and contains one row per video file, formatted as `video_file:H,M,S`. For example, this could be `kage1_20240420_000002.mp4:0,0,6`. The hours, minutes, and seconds represent the offset relative to time `00:00:00` of that day. These values are extracted from the first video frame using computer vision. Negative, or otherwise impossible values indicate an error in this extraction process.

2. The `corrected_timestamps.pkl` file. There is one per day, stored in `kageN/analysis/dlc_output/YYYY/MM/DD/`. This file contains a dictionary mapping each pose filename to an array of corrected timestamps, expressed in seconds since the start of the hour. The first element should match the offset in the `adjustments.txt` file, and the rest should be derived by adding the frame timestamps (extracted from the .mp4 file) to this offset.

As a result of this process, the dataframe `df` will now have a `start_datetime` column with the exact start time of each video. Moreover, we will obtain a `frame_timestamps` dictionary, mapping each video segment, identified by a `(kage, date, hour)` tuple, to an array of timestamps expressed in seconds elapsed since the start of each video.

In [6]:
df, frame_timestamps = extract_datetimes(df)

### Quality control 1: start datetime mismatches between `adjustments.txt` and `corrected_timestamps.pkl`
Some warnings may have appeared during the adjustment, flagging invalid adjustments values or mismatches between the `adjustments.txt` and the `corrected_timestamps.pkl`. We have marked all such problematic segments as having a `start_datetime` of `NaT` (Not a Time) in the dataframe.

In [7]:
invalid_datetimes = df[df["start_datetime"].isna()]
if not invalid_datetimes.empty:
    print(
        f"Found {len(invalid_datetimes)} videos with invalid adjustments",
        "or mismatches between the adjustment and corrected_timestamps.pkl.",
    )
    invalid_datetimes[["start_datetime"]]
else:
    print("All videos have valid start_datetimes.")

All videos have valid start_datetimes.

We can open the first frame of each problematic video and look at the timestamps burned into the top-left corner.

In [8]:
for idx, row in invalid_datetimes.iterrows():
    print(idx)
    show_first_frame_corner(row["video_file_path"])

Below, we will manually enter the correct start datetimes for each problematic video,
as a dictionary mapping `(kage, date, hour)` tuples to datetimes in the format `YYYY-MM-DD HH:MM:SS`.
If there are no problematic videos, this dictionary can be empty.

In [9]:
manual_start_datetimes = {
    # ("kage1", "20240426", "07"): "2024-04-26 07:00:06",
}

for (kage, date, hour), start_datetime in manual_start_datetimes.items():
    df.loc[(kage, date, hour), "start_datetime"] = pd.to_datetime(
        start_datetime, format="%Y-%m-%d %H:%M:%S"
    )

# All start datetimes should now be valid.
assert df["start_datetime"].notna().all(), "Some start datetimes are still NaT"

Now we can derive the precise datetime timestamps for each frame by adding the known `start_datetime` to the frame timestamps (which are in seconds elapsed).

We can also derive the `end_datetime` for each video as the last timestamp.

We also derive a `timestamps_datetime` dictionary, mapping each video segment, identified by a `(kage, date, hour)` tuple, to an array of precise datetime objects for each frame.

In [10]:
df["end_datetime"] = pd.Series(dtype="datetime64[us]", index=df.index)
timestamps_datetime = {}
for (kage, date, hour), seconds_elapsed in tqdm(frame_timestamps.items()):
    start_datetime = df.loc[(kage, date, hour), "start_datetime"]
    timedelta = pd.to_timedelta(seconds_elapsed, unit="s")
    datetime_stamps = (start_datetime + timedelta).as_unit("us")
    # Derive the end datetimes from the last timestamp of each video.
    df.loc[(kage, date, hour), "end_datetime"] = datetime_stamps[-1]
    timestamps_datetime[(kage, date, hour)] = datetime_stamps

# Ensure consistent microsecond precision for datetime columns
df["start_datetime"] = df["start_datetime"].dt.as_unit("us")
df["end_datetime"] = df["end_datetime"].dt.as_unit("us")

# Reorder columns for readability
df = df[
    [
        "start_datetime",
        "end_datetime",
        "n_frames",
        "n_channels",
        "height",
        "width",
        "pose_file_path",
        "video_file_path",
    ]
]
df.head()

100%|██████████| 3449/3449 [00:05<00:00, 586.84it/s]

                         start_datetime               end_datetime  n_frames  \
kage  date     hour
kage1 20240723 11   2024-07-23 11:01:07 2024-07-23 11:59:59.483284      7067
               12   2024-07-23 12:01:08 2024-07-23 12:59:59.492319      7065
               13   2024-07-23 13:01:07 2024-07-23 13:59:59.482941      7067
               14   2024-07-23 14:01:07 2024-07-23 14:59:59.489167      7067
               15   2024-07-23 15:01:07 2024-07-23 15:59:59.484364      7067

                     n_channels  height  width  \
kage  date     hour
kage1 20240723 11             3     376    500
               12             3     376    500
               13             3     376    500
               14             3     376    500
               15             3     376    500

                                                        pose_file_path  \
kage  date     hour
kage1 20240723 11    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               12    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               14    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

                                                       video_file_path
kage  date     hour
kage1 20240723 11    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               12    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               14    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

### Quality control 2: Number of frames mismatch between video and timestamps
Let's check if the number of frame timestamps in each segment matches the number of frames in the video.
If some video frames are missing timestamps, we will extract them anew from the video file and fill the gaps with linear interpolation, if needed.
If this process still results in a mismatch, we will raise an error. Finally, we will update the `frame_timestamps` and `timestamps_datetime` dictionaries as well as the `end_datetime` column in the dataframe with the new corrected timestamps.

In [11]:
for (kage, date, hour), seconds_elapsed in tqdm(frame_timestamps.items()):
    n_frames = df.loc[(kage, date, hour), "n_frames"]
    if len(seconds_elapsed) != n_frames:
        print(
            f"Mismatch for {kage} {date} {hour}: {len(seconds_elapsed)} "
            f"frame timestamps vs {n_frames} video frames."
        )

        # Let's extract frame timestamps directly from the video
        # and interpolate missing timestamps if needed.
        new_seconds_elapsed = extract_frame_timestamps(
            df.loc[(kage, date, hour), "video_file_path"],
            expected_n_frames=n_frames,
        )

        # Check if the new timestamps now match the expected number of frames.
        if len(new_seconds_elapsed) != n_frames:
            raise ValueError(
                f"New timestamps length {len(new_seconds_elapsed)} still "
                f"does not match expected {n_frames} frames."
            )

        # Update the timestamps with the new ones.
        frame_timestamps[(kage, date, hour)] = new_seconds_elapsed
        # Re-compute datetime stamps from the known start datetime.
        start_datetime = df.loc[(kage, date, hour), "start_datetime"]
        timedelta = pd.to_timedelta(new_seconds_elapsed, unit="s")
        datetime_stamps = (start_datetime + timedelta).as_unit("us")
        # Re-derive the end datetimes from the last timestamp of each video.
        df.loc[(kage, date, hour), "end_datetime"] = datetime_stamps[-1]
        timestamps_datetime[(kage, date, hour)] = datetime_stamps

# Re-enforce microsecond precision after any updates
df["end_datetime"] = df["end_datetime"].dt.as_unit("us")

  0%|          | 0/3449 [00:00<?, ?it/s]

Mismatch for kage1 20240812 08: 7066 frame timestamps vs 7067 video frames.

2026-03-03 18:16:19.790 | WARNING  | smart_kages_movement.datetime:extract_frame_timestamps:264 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_27235/1182810314.py:11: UserWarning: Video /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/kage1/videos/2024/08/12/kage1_20240812_080103.mp4 has 1 missing timestamps. The following frames will be filled with linear interpolation: [7066]
  new_seconds_elapsed = extract_frame_timestamps(

 14%|█▍        | 478/3449 [00:03<00:21, 137.65it/s]

Mismatch for kage1 20240823 07: 7061 frame timestamps vs 7062 video frames.

2026-03-03 18:16:22.565 | WARNING  | smart_kages_movement.datetime:extract_frame_timestamps:264 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_27235/1182810314.py:11: UserWarning: Video /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/kage1/videos/2024/08/23/kage1_20240823_070104.mp4 has 1 missing timestamps. The following frames will be filled with linear interpolation: [7061]
  new_seconds_elapsed = extract_frame_timestamps(

 21%|██▏       | 741/3449 [00:06<00:23, 114.89it/s]

Mismatch for kage1 20240908 02: 7066 frame timestamps vs 7067 video frames.

2026-03-03 18:16:25.566 | WARNING  | smart_kages_movement.datetime:extract_frame_timestamps:264 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_27235/1182810314.py:11: UserWarning: Video /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/kage1/videos/2024/09/08/kage1_20240908_020103.mp4 has 1 missing timestamps. The following frames will be filled with linear interpolation: [7066]
  new_seconds_elapsed = extract_frame_timestamps(

 32%|███▏      | 1120/3449 [00:09<00:19, 120.04it/s]

Mismatch for kage22 20240808 16: 7066 frame timestamps vs 7067 video frames.

2026-03-03 18:16:28.356 | WARNING  | smart_kages_movement.datetime:extract_frame_timestamps:264 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_27235/1182810314.py:11: UserWarning: Video /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/kage22/videos/2024/08/08/kage22_20240808_160103.mp4 has 1 missing timestamps. The following frames will be filled with linear interpolation: [7066]
  new_seconds_elapsed = extract_frame_timestamps(

 45%|████▌     | 1567/3449 [00:12<00:13, 135.10it/s]

Mismatch for kage28 20240827 20: 7060 frame timestamps vs 7061 video frames.

2026-03-03 18:16:31.253 | WARNING  | smart_kages_movement.datetime:extract_frame_timestamps:264 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_27235/1182810314.py:11: UserWarning: Video /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/kage28/videos/2024/08/27/kage28_20240827_200104.mp4 has 1 missing timestamps. The following frames will be filled with linear interpolation: [7060]
  new_seconds_elapsed = extract_frame_timestamps(

100%|██████████| 3449/3449 [00:14<00:00, 230.84it/s]

### Quality control 3: Overlapping segments
Let's find out if there are any overlapping segments based on their `start_datetime` and `end_datetime`.

In [12]:
overlaps = find_segment_overlaps(df)
overlaps

No overlapping segments found.

We suspect that overlaps might be due to incorrect adjustments for the videos mentioned in `segment_A`, i.e. the timestamps of the first frame being incorrectly read by the computer vision algorithm. We can confirm this and manually correct this, as we did above.

In [13]:
if overlaps is None:
    print("No need for inspection, no overlaps found.")
    print("You can skip the next cell.")
else:
    for _, row in overlaps.iterrows():
        segment_A = row["segment_A"]
        video_path = df.loc[segment_A, "video_file_path"]
        video = sio.load_video(video_path)
        first_frame = video[0]  # Get the first frame
        # matplotlib show the first frame
        plt.imshow(first_frame[:20, :300])
        plt.axis("off")
        print(segment_A)
        plt.show()

No need for inspection, no overlaps found.
You can skip the next cell.

In [14]:
more_manual_start_datetimes = {
    # ("kage1", "20240426", "07"): "2024-04-26 07:00:06",
}

for (kage, date, hour), start_datetime in more_manual_start_datetimes.items():
    df.loc[(kage, date, hour), "start_datetime"] = pd.to_datetime(
        start_datetime, format="%Y-%m-%d %H:%M:%S"
    )
    start = pd.Timestamp(start_datetime)
    timedelta = pd.to_timedelta(frame_timestamps[(kage, date, hour)], unit="s")
    timestamps_datetime[(kage, date, hour)] = start + timedelta
    df.loc[(kage, date, hour), "end_datetime"] = timestamps_datetime[
        (kage, date, hour)
    ][-1]

# Re-enforce microsecond precision after any manual updates
df["start_datetime"] = df["start_datetime"].dt.as_unit("us")
df["end_datetime"] = df["end_datetime"].dt.as_unit("us")

In [15]:
df.head()

                         start_datetime               end_datetime  n_frames  \
kage  date     hour
kage1 20240723 11   2024-07-23 11:01:07 2024-07-23 11:59:59.483284      7067
               12   2024-07-23 12:01:08 2024-07-23 12:59:59.492319      7065
               13   2024-07-23 13:01:07 2024-07-23 13:59:59.482941      7067
               14   2024-07-23 14:01:07 2024-07-23 14:59:59.489167      7067
               15   2024-07-23 15:01:07 2024-07-23 15:59:59.484364      7067

                     n_channels  height  width  \
kage  date     hour
kage1 20240723 11             3     376    500
               12             3     376    500
               13             3     376    500
               14             3     376    500
               15             3     376    500

                                                        pose_file_path  \
kage  date     hour
kage1 20240723 11    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               12    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               14    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

                                                       video_file_path
kage  date     hour
kage1 20240723 11    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               12    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               14    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

### Quality control 4: Some final sanity checks
Everything should be fine now, but let's run some sanity checks

In [16]:
# All start datetimes should now be valid.
assert df["start_datetime"].notna().all(), "Some start datetimes are still NaT"

# Now, there should be no more overlaps
overlaps = find_segment_overlaps(df)
assert overlaps is None, (
    "There are still overlapping segments after manual adjustments."
)

# For each kage, the start_datetime values should be monotonic increasing
for kage in df.index.get_level_values("kage").unique():
    kage_start_datetimes = df.loc[kage, "start_datetime"].values
    assert np.all(np.diff(kage_start_datetimes) >= pd.Timedelta(0)), (
        f"Start datetimes for kage {kage} are not monotonic increasing."
    )

# For each row, the end_datetime should be greater than the start_datetime
assert np.all(df["end_datetime"] > df["start_datetime"]), (
    "Some end datetimes are not greater than start datetimes."
)

No overlapping segments found.

## Save the timestamps to txt files
We save the datetime timestamps to .txt files, with one file per 1-hour video segment.

We also store the paths to these .txt files in the `df` dataframe, in a new column called `timestamps_file_path`.

In [17]:
timestamps_dir = save_dir / "timestamps"
timestamps_dir.mkdir(parents=True, exist_ok=True)


timestamps_file_paths = {}
items = list(timestamps_datetime.items())

if USE_MULTIPROCESSING:
    with ProcessPoolExecutor() as ex:
        futures = {
            ex.submit(save_segment_timestamps, it[0], it[1], timestamps_dir): it[0]
            for it in items
        }
        for fut in tqdm(as_completed(futures), total=len(futures)):
            key, path = fut.result()
            timestamps_file_paths[key] = path
else:
    for it in tqdm(items, total=len(items)):
        key, path = save_segment_timestamps(it[0], it[1], timestamps_dir)
        timestamps_file_paths[key] = path

# Add timestamps file paths to the DataFrame in one go
paths_s = pd.Series(timestamps_file_paths, name="timestamps_file_path")
paths_s.index = pd.MultiIndex.from_tuples(paths_s.index, names=df.index.names)
df.loc[paths_s.index, "timestamps_file_path"] = paths_s.values

print(f"Timestamps saved to {timestamps_dir}.")

100%|██████████| 3449/3449 [00:26<00:00, 131.57it/s]

Timestamps saved to /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/movement_analysis/timestamps.

## Save the dataframes as CSV files
Finally, we save the `df` dataframe to a CSV file for later use.

In [18]:
df.to_csv(save_dir / "all_segments.csv")
print(f"Dataframe saved to {save_dir}.")

Dataframe saved to /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/movement_analysis.