# Load data from Smart-Kages into `movement` datasets
Load all DLC .h5 pose files for each kage and concatenate them
into a single `movement` dataset.

Assign a datetime index across the `time` dimension for easy access.

Save the resulting dataset to a netCDF file.

In [1]:
from pathlib import Path

import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from tqdm import tqdm

from smart_kages_movement.loading import kage_to_movement_ds

## Configuration
Define some global variables and paths.

In [2]:
FPS = 2  # frames per second
PIXELS_PER_CM = 10  # pixels per centimetre (need to double-check this)

# Configure seaborn for prettier plots
sns.set_context("notebook")
sns.set_style("ticks")

In [3]:
data_dir = Path.home() / "Data" / "Smart-Kages" / "2024-Jul-Sep"
analysis_dir = data_dir / "movement_analysis"
# csv file generated by the 01 notebook
df_path = analysis_dir / "all_segments.csv"


for path in [data_dir, analysis_dir, df_path]:
    if not path.exists():
        print(f"Path does not exist: {path}")

## Load CSV files as dataframe

We load the dataframe containing the paths to all the DLC .h5 files, which is generated in the 01 notebook.

In [4]:
df = pd.read_csv(
    df_path,
    index_col=[0, 1, 2],
    dtype={
        "date": str,
        "hour": str,
        "n_frames": int,
    },
    parse_dates=["start_datetime", "end_datetime"],
)

# Take /DB out of the timestamps_file_path (timestamps were moved since creation of CSV)
df["timestamps_file_path"] = df["timestamps_file_path"].apply(
    lambda x: x.replace("/DB", "")
)

df.head()

                         start_datetime               end_datetime  n_frames  \
kage  date     hour
kage1 20240723 11   2024-07-23 11:01:07 2024-07-23 11:59:59.483284      7067
               12   2024-07-23 12:01:08 2024-07-23 12:59:59.492319      7065
               13   2024-07-23 13:01:07 2024-07-23 13:59:59.482941      7067
               14   2024-07-23 14:01:07 2024-07-23 14:59:59.489167      7067
               15   2024-07-23 15:01:07 2024-07-23 15:59:59.484364      7067

                     n_channels  height  width  \
kage  date     hour
kage1 20240723 11             3     376    500
               12             3     376    500
               13             3     376    500
               14             3     376    500
               15             3     376    500

                                                        pose_file_path  \
kage  date     hour
kage1 20240723 11    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               12    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               14    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

                                                       video_file_path  \
kage  date     hour
kage1 20240723 11    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               12    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               14    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

                                                  timestamps_file_path
kage  date     hour
kage1 20240723 11    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               12    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               13    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               14    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...
               15    /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-...

We see that the dataframe holds various information on each 1-hour segment of the data.

The index is hierarchical, organising the data first by `kage`, then by `date`, and finally by `hour`.

Of special relevance to us here:
- Paths: `pose_file_path`, `video_file_path`, `timestamps_file_path`
- `start_datetime` and `end_datetime` for each segment

## Convert all data from a given kage a `movement` dataset

We use `kage_to_movement_ds` from `smart_kages_movement.loading` to load all
DLC `.h5` files for a kage and merge them into a single `movement` dataset.

We also assign a background image to each kage, which is used for visualisation purposes.

Then, we save the combined `movement` datasets for each kage to a netCDF file.
We also save the background image for each kage in the same directory.

In [ ]:
SKIP_EXISTING = True  # Set this to False to overwrite existing files

In [10]:
problematic_dfs = []

for kage in tqdm(df.index.get_level_values("kage").unique()):
    # Path to save the netCDF files and background image.
    kage_dir = analysis_dir / kage
    kage_dir.mkdir(parents=True, exist_ok=True)
    ds_file_path = kage_dir / f"{kage}.nc"
    img_file_path = kage_dir / f"{kage}_background.png"

    if ds_file_path.exists() and SKIP_EXISTING:
        print(
            f"Found existing netCDF file for {kage} at {ds_file_path}. "
            f"Will not overwrite."
        )
        continue
    else:
        # Create movement dataset for each kage
        ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)
        if df_prob is not None:
            problematic_dfs.append(df_prob)
        print(f"Converted data from {kage} to a 'movement' xarray Dataset.")

        # Save the dataset to a NetCDF file
        ds.to_netcdf(ds_file_path, mode="w", engine="netcdf4", format="NETCDF4")
        print(f"Dataset for {kage} saved to {ds_file_path}.")

        # Save the background image
        plt.imsave(img_file_path, img)
        print(f"Background image for {kage} saved to {img_file_path}.\n")

        # Free up memory
        del ds, img, df_prob

df_problematic = pd.concat(problematic_dfs) if problematic_dfs else pd.DataFrame()

  0%|          | 0/3 [00:00<?, ?it/s]

Processing kage: kage1
Number of days: 50
Number of 1-hour segments: 1178
Loaded background image for kage1 from /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/kage1/videos/2024/08/17/kage1_20240817_000103.mp4

Converted data from kage1 to a 'movement' xarray Dataset.

 33%|███▎      | 1/3 [00:28<00:57, 28.90s/it]

Dataset for kage1 saved to /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/movement_analysis/kage1/kage1.nc.
Background image for kage1 saved to /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/movement_analysis/kage1/kage1_background.png.

Processing kage: kage22
Number of days: 50
Number of 1-hour segments: 1177

2026-03-03 18:21:07.788 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240723 16: DLC has 7067 tracked frames but video has 7062 frames. Truncating to 7062.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:07.838 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240723 18: DLC has 7065 tracked frames but video has 7060 frames. Truncating to 7060.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:07.861 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240723 19: DLC has 7067 tracked frames but video has 7061 frames. Truncating to 7061.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:08.482 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240724 21: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:12.779 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240801 23: DLC has 7067 tracked frames but video has 7062 frames. Truncating to 7062.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:17.209 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240809 16: DLC has 7067 tracked frames but video has 7065 frames. Truncating to 7065.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:19.386 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240812 21: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:19.433 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240812 23: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:20.008 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240813 23: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:20.050 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240814 01: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:20.068 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240814 02: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:20.130 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240814 05: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:20.152 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240814 06: DLC has 7065 tracked frames but video has 7064 frames. Truncating to 7064.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:20.176 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240814 07: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:20.409 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240814 17: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:20.540 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240814 23: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:23.011 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240819 21: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:25.732 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240824 22: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:34.116 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240909 22: DLC has 7065 tracked frames but video has 7064 frames. Truncating to 7064.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:34.445 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage22 20240910 12: DLC has 7067 tracked frames but video has 7066 frames. Truncating to 7066.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

Truncated 20 segments (too many tracked frames).
Loaded background image for kage22 from /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/kage22/videos/2024/08/17/kage22_20240817_000103.mp4

Converted data from kage22 to a 'movement' xarray Dataset.

 67%|██████▋   | 2/3 [00:59<00:29, 29.85s/it]

Dataset for kage22 saved to /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/movement_analysis/kage22/kage22.nc.
Background image for kage22 saved to /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/movement_analysis/kage22/kage22_background.png.

Processing kage: kage28
Number of days: 50
Number of 1-hour segments: 1094

2026-03-03 18:21:38.229 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240723 17: DLC has 7067 tracked frames but video has 7039 frames. Truncating to 7039.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.260 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240723 20: DLC has 7065 tracked frames but video has 7054 frames. Truncating to 7054.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.284 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240723 21: DLC has 7067 tracked frames but video has 7020 frames. Truncating to 7020.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.322 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240723 22: DLC has 7067 tracked frames but video has 7032 frames. Truncating to 7032.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.432 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 02: DLC has 7067 tracked frames but video has 7012 frames. Truncating to 7012.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.461 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 03: DLC has 7067 tracked frames but video has 7052 frames. Truncating to 7052.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.494 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 04: DLC has 7067 tracked frames but video has 7031 frames. Truncating to 7031.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.524 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 05: DLC has 7067 tracked frames but video has 6996 frames. Truncating to 6996.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.547 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 06: DLC has 7067 tracked frames but video has 7043 frames. Truncating to 7043.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.564 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 07: DLC has 7067 tracked frames but video has 7028 frames. Truncating to 7028.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.580 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 08: DLC has 7067 tracked frames but video has 7023 frames. Truncating to 7023.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.597 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 09: DLC has 7065 tracked frames but video has 7046 frames. Truncating to 7046.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.612 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 10: DLC has 7067 tracked frames but video has 7023 frames. Truncating to 7023.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.628 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 11: DLC has 7067 tracked frames but video has 7052 frames. Truncating to 7052.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.643 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 12: DLC has 7065 tracked frames but video has 7053 frames. Truncating to 7053.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.658 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 13: DLC has 7067 tracked frames but video has 7042 frames. Truncating to 7042.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.673 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 14: DLC has 7067 tracked frames but video has 7036 frames. Truncating to 7036.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.688 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 15: DLC has 7065 tracked frames but video has 7048 frames. Truncating to 7048.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.703 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 16: DLC has 7067 tracked frames but video has 7024 frames. Truncating to 7024.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.719 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 17: DLC has 7067 tracked frames but video has 7061 frames. Truncating to 7061.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.739 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 18: DLC has 7067 tracked frames but video has 7051 frames. Truncating to 7051.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.754 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 19: DLC has 7067 tracked frames but video has 7037 frames. Truncating to 7037.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.771 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 20: DLC has 7067 tracked frames but video has 7037 frames. Truncating to 7037.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.786 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 21: DLC has 7067 tracked frames but video has 7021 frames. Truncating to 7021.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.802 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 22: DLC has 7065 tracked frames but video has 7030 frames. Truncating to 7030.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.820 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240724 23: DLC has 7067 tracked frames but video has 7032 frames. Truncating to 7032.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.864 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 02: DLC has 7067 tracked frames but video has 7029 frames. Truncating to 7029.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.880 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 03: DLC has 7067 tracked frames but video has 7020 frames. Truncating to 7020.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.898 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 04: DLC has 7067 tracked frames but video has 7017 frames. Truncating to 7017.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.913 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 05: DLC has 7065 tracked frames but video has 7046 frames. Truncating to 7046.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.935 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 06: DLC has 7067 tracked frames but video has 7021 frames. Truncating to 7021.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.956 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 07: DLC has 7067 tracked frames but video has 7043 frames. Truncating to 7043.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.973 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 08: DLC has 7067 tracked frames but video has 7029 frames. Truncating to 7029.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:38.989 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 09: DLC has 7067 tracked frames but video has 7026 frames. Truncating to 7026.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.005 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 10: DLC has 7067 tracked frames but video has 7038 frames. Truncating to 7038.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.025 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 11: DLC has 7063 tracked frames but video has 7043 frames. Truncating to 7043.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.041 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 12: DLC has 7067 tracked frames but video has 7044 frames. Truncating to 7044.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.064 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 13: DLC has 7067 tracked frames but video has 7059 frames. Truncating to 7059.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.082 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 14: DLC has 7065 tracked frames but video has 7044 frames. Truncating to 7044.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.100 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 15: DLC has 7067 tracked frames but video has 7050 frames. Truncating to 7050.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.120 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 16: DLC has 7067 tracked frames but video has 7048 frames. Truncating to 7048.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.135 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 17: DLC has 7065 tracked frames but video has 7031 frames. Truncating to 7031.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.149 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 18: DLC has 7067 tracked frames but video has 7061 frames. Truncating to 7061.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.167 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 19: DLC has 7067 tracked frames but video has 7058 frames. Truncating to 7058.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.187 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 20: DLC has 7067 tracked frames but video has 7060 frames. Truncating to 7060.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.207 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 21: DLC has 7067 tracked frames but video has 7052 frames. Truncating to 7052.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.223 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 22: DLC has 7067 tracked frames but video has 7044 frames. Truncating to 7044.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.243 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240725 23: DLC has 7067 tracked frames but video has 7040 frames. Truncating to 7040.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.292 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 02: DLC has 7067 tracked frames but video has 7045 frames. Truncating to 7045.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.311 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 03: DLC has 7065 tracked frames but video has 7048 frames. Truncating to 7048.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.330 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 04: DLC has 7067 tracked frames but video has 7007 frames. Truncating to 7007.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.345 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 05: DLC has 7067 tracked frames but video has 7003 frames. Truncating to 7003.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.365 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 06: DLC has 7065 tracked frames but video has 7049 frames. Truncating to 7049.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.384 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 07: DLC has 7067 tracked frames but video has 7019 frames. Truncating to 7019.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.398 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 08: DLC has 7067 tracked frames but video has 7018 frames. Truncating to 7018.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.438 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 09: DLC has 7065 tracked frames but video has 7046 frames. Truncating to 7046.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.462 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 10: DLC has 7067 tracked frames but video has 7045 frames. Truncating to 7045.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)

2026-03-03 18:21:39.493 | WARNING  | smart_kages_movement.loading:kage_to_movement_ds:135 - /var/folders/w3/q74_bsm5379bzb0hkt1n4bzm0000gn/T/ipykernel_28221/898087253.py:18: UserWarning: kage28 20240726 11: DLC has 7067 tracked frames but video has 7046 frames. Truncating to 7046.
  ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)


Truncated 970 segments (too many tracked frames).
Loaded background image for kage28 from /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/kage28/videos/2024/08/17/kage28_20240817_030103.mp4

Converted data from kage28 to a 'movement' xarray Dataset.

100%|██████████| 3/3 [01:24<00:00, 28.17s/it]

Dataset for kage28 saved to /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/movement_analysis/kage28/kage28.nc.
Background image for kage28 saved to /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/movement_analysis/kage28/kage28_background.png.

## Save diagnostics on skipped segments

Some segments may have been truncated or skipped during the loading process due to mismatches between the number of tracked timepoints and the number of video frames.

We will save the dataframe listing those mismatches, along with the action taken (truncated or skipped), to a CSV file for future reference.

In [12]:
if not df_problematic.empty:
    df_problematic.to_csv(analysis_dir / "segments_with_frame_mismatches.csv")
    print(
        "Saved dataframe of segments with frame mismatches to "
        f"{analysis_dir / 'segments_with_frame_mismatches.csv'}."
    )
df_problematic

Saved dataframe of segments with frame mismatches to /Users/nsirmpilatze/Data/Smart-Kages/2024-Jul-Sep/movement_analysis/segments_with_frame_mismatches.csv.

                      n_frames  n_tracked_frames     action
kage   date     hour
kage22 20240723 16        7062              7067  truncated
                18        7060              7065  truncated
                19        7061              7067  truncated
       20240724 21        7066              7067  truncated
       20240801 23        7062              7067  truncated
...                        ...               ...        ...
kage28 20240910 08        7022              7067  truncated
                09        7018              7067  truncated
                10        7036              7067  truncated
                11        7040              7063  truncated
                12        1690              1695  truncated

[990 rows x 3 columns]