# Load data from Smart-Kages into `movement` datasets
Load all DLC .h5 pose files for each kage and concatenate them
into a single `movement` dataset.

Assign a datetime index across the `time` dimension for easy access.

Save the resulting dataset to a netCDF file.

In [1]:
from pathlib import Path

import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from tqdm import tqdm

from smart_kages_movement.loading import kage_to_movement_ds

## Configuration
Define some global variables and paths.

In [3]:
FPS = 2  # frames per second
PIXELS_PER_CM = 10  # pixels per centimetre (need to double-check this)

# Configure seaborn for prettier plots
sns.set_context("notebook")
sns.set_style("ticks")

In [4]:
project_dir = Path("/mnt/Data/Smart-Kages/2024-04-Apr-May-Downs")
analysis_dir = project_dir / "movement_analysis"
# csv file generated by the 01 notebook
df_path = analysis_dir / "all_segments.csv"


for path in [project_dir, analysis_dir, df_path]:
    if not path.exists():
        print(f"Path does not exist: {path}")

## Load CSV files as dataframe

We load the dataframe containing the paths to all the DLC .h5 files, which is generated in the 01 notebook.

In [5]:
df = pd.read_csv(
    df_path,
    index_col=[0, 1, 2],
    dtype={
        "date": str,
        "hour": str,
        "n_frames": int,
    },
    parse_dates=["start_datetime", "end_datetime"],
)

# Take /DB out of the timestamps_file_path (timestamps were moved since creation of CSV)
df["timestamps_file_path"] = df["timestamps_file_path"].apply(
    lambda x: x.replace("/DB", "")
)

df.head()

                         start_datetime                  end_datetime  \
kage  date     hour
kage1 20240403 09   2024-04-03 09:54:24 2024-04-03 09:59:59.495354911
               10   2024-04-03 10:00:06 2024-04-03 10:59:59.506997932
               11   2024-04-03 11:01:07 2024-04-03 11:59:59.505496638
               12   2024-04-03 12:01:08 2024-04-03 12:59:59.510819259
               13   2024-04-03 13:01:07 2024-04-03 13:59:59.509458847

                     n_frames  n_channels  height  width  \
kage  date     hour
kage1 20240403 09         665           3     376    500
               10        7183           3     376    500
               11        7064           1     376    500
               12        7059           3     376    500
               13        7058           3     376    500

                                                        pose_file_path  \
kage  date     hour
kage1 20240403 09    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...
               10    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...
               11    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...
               12    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...
               13    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...

                                                       video_file_path  \
kage  date     hour
kage1 20240403 09    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...
               10    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...
               11    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...
               12    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...
               13    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/DB...

                                                  timestamps_file_path
kage  date     hour
kage1 20240403 09    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/mo...
               10    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/mo...
               11    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/mo...
               12    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/mo...
               13    /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/mo...

We see that the dataframe holds various information on each 1-hour segment of the data.

The index is hierarchical, organising the data first by `kage`, then by `date`, and finally by `hour`.

Of special relevance to us here:
- Paths: `pose_file_path`, `video_file_path`, `timestamps_file_path`
- `start_datetime` and `end_datetime` for each segment

## Convert all data from a given kage a `movement` dataset

We use `kage_to_movement_ds` from `smart_kages_movement.loading` to load all
DLC `.h5` files for a kage and merge them into a single `movement` dataset.

We also assign a background image to each kage, which is used for visualisation purposes.

Then, we save the combined `movement` datasets for each kage to a netCDF file.
We also save the background image for each kage in the same directory.

In [6]:
SKIP_EXISTING = True  # Set this to False to overwrite existing files

In [7]:
problematic_dfs = []

for kage in tqdm(df.index.get_level_values("kage").unique()):
    # Path to save the netCDF files and background image.
    kage_dir = analysis_dir / kage
    kage_dir.mkdir(parents=True, exist_ok=True)
    ds_file_path = kage_dir / f"{kage}.nc"
    img_file_path = kage_dir / f"{kage}_background.png"

    if ds_file_path.exists() and SKIP_EXISTING:
        print(
            f"Found existing netCDF file for {kage} at {ds_file_path}. "
            f"Will not overwrite."
        )
        continue
    else:
        # Create movement dataset for each kage
        ds, img, df_prob = kage_to_movement_ds(df, kage, fps=FPS)
        if df_prob is not None:
            problematic_dfs.append(df_prob)
        print(f"Converted data from {kage} to a 'movement' xarray Dataset.")

        # Save the dataset to a NetCDF file
        ds.to_netcdf(ds_file_path, mode="w", engine="netcdf4", format="NETCDF4")
        print(f"Dataset for {kage} saved to {ds_file_path}.")

        # Save the background image
        plt.imsave(img_file_path, img)
        print(f"Background image for {kage} saved to {img_file_path}.\n")

        # Free up memory
        del ds, img, df_prob

df_problematic = pd.concat(problematic_dfs) if problematic_dfs else pd.DataFrame()

100%|██████████| 33/33 [00:00<00:00, 15373.99it/s]

Found existing netCDF file for kage1 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage1/kage1.nc. Will not overwrite.
Found existing netCDF file for kage10 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage10/kage10.nc. Will not overwrite.
Found existing netCDF file for kage11 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage11/kage11.nc. Will not overwrite.
Found existing netCDF file for kage12 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage12/kage12.nc. Will not overwrite.
Found existing netCDF file for kage13 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage13/kage13.nc. Will not overwrite.
Found existing netCDF file for kage14 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage14/kage14.nc. Will not overwrite.
Found existing netCDF file for kage15 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage15/kage15.nc. Will not overwrite.
Found existing netCDF file for kage16 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage16/kage16.nc. Will not overwrite.
Found existing netCDF file for kage17 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage17/kage17.nc. Will not overwrite.
Found existing netCDF file for kage18 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage18/kage18.nc. Will not overwrite.
Found existing netCDF file for kage19 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage19/kage19.nc. Will not overwrite.
Found existing netCDF file for kage2 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage2/kage2.nc. Will not overwrite.
Found existing netCDF file for kage20 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage20/kage20.nc. Will not overwrite.
Found existing netCDF file for kage21 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage21/kage21.nc. Will not overwrite.
Found existing netCDF file for kage22 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage22/kage22.nc. Will not overwrite.
Found existing netCDF file for kage23 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage23/kage23.nc. Will not overwrite.
Found existing netCDF file for kage24 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage24/kage24.nc. Will not overwrite.
Found existing netCDF file for kage25 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage25/kage25.nc. Will not overwrite.
Found existing netCDF file for kage26 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage26/kage26.nc. Will not overwrite.
Found existing netCDF file for kage27 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage27/kage27.nc. Will not overwrite.
Found existing netCDF file for kage28 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage28/kage28.nc. Will not overwrite.
Found existing netCDF file for kage29 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage29/kage29.nc. Will not overwrite.
Found existing netCDF file for kage3 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage3/kage3.nc. Will not overwrite.
Found existing netCDF file for kage30 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage30/kage30.nc. Will not overwrite.
Found existing netCDF file for kage31 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage31/kage31.nc. Will not overwrite.
Found existing netCDF file for kage32 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage32/kage32.nc. Will not overwrite.
Found existing netCDF file for kage33 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage33/kage33.nc. Will not overwrite.
Found existing netCDF file for kage4 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage4/kage4.nc. Will not overwrite.
Found existing netCDF file for kage5 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage5/kage5.nc. Will not overwrite.
Found existing netCDF file for kage6 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage6/kage6.nc. Will not overwrite.
Found existing netCDF file for kage7 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage7/kage7.nc. Will not overwrite.
Found existing netCDF file for kage8 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage8/kage8.nc. Will not overwrite.
Found existing netCDF file for kage9 at /mnt/Data/Smart-Kages/2024-04-Apr-May-Downs/movement_analysis/kage9/kage9.nc. Will not overwrite.

## Save diagnostics on skipped segments

Some segments may have been truncated or skipped during the loading process due to mismatches between the number of tracked timepoints and the number of video frames.

We will save the dataframe listing those mismatches, along with the action taken (truncated or skipped), to a CSV file for future reference.

In [8]:
if not df_problematic.empty:
    df_problematic.to_csv(analysis_dir / "segments_with_frame_mismatches.csv")
    print(
        "Saved dataframe of segments with frame mismatches to "
        f"{analysis_dir / 'segments_with_frame_mismatches.csv'}."
    )
df_problematic

Empty DataFrame
Columns: []
Index: []